#ifndef BLOCK_CONSTANTS_H
#define BLOCK_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, BlockType) {
    BLOCK_TYPE_NONE,
    BLOCK_TYPE_SHOT_BLOCK_REFORM,
    BLOCK_TYPE_BOMB_BLOCK_REFORM,
    BLOCK_TYPE_SPEEDBOOSTER_BLOCK_REFORM,
    BLOCK_TYPE_CRUMBLE,
    BLOCK_TYPE_SLOW_CRUMBLE,
    BLOCK_TYPE_MISSILE_NEVER_REFORM,
    BLOCK_TYPE_MISSILE_NO_REFORM,
    BLOCK_TYPE_SUPER_MISSILE_NEVER_REFORM,
    BLOCK_TYPE_SUPER_MISSILE_NO_REFORM,
    BLOCK_TYPE_POWER_BOMB_NEVER_REFORM,
    BLOCK_TYPE_SCREW_NO_REFORM,
    BLOCK_TYPE_SPEEDBOOSTER_BLOCK_NO_REFORM,
    BLOCK_TYPE_BOMB_BLOCK_NEVER_REFORM,
    BLOCK_TYPE_VERTICAL_BOMB_CHAIN1,
    BLOCK_TYPE_VERTICAL_BOMB_CHAIN2,
    BLOCK_TYPE_VERTICAL_BOMB_CHAIN3,
    BLOCK_TYPE_VERTICAL_BOMB_CHAIN4,
    BLOCK_TYPE_HORIZONTAL_BOMB_CHAIN1,
    BLOCK_TYPE_HORIZONTAL_BOMB_CHAIN2,
    BLOCK_TYPE_HORIZONTAL_BOMB_CHAIN3,
    BLOCK_TYPE_HORIZONTAL_BOMB_CHAIN4,

    BLOCK_TYPE_COUNT
};

MAKE_ENUM(u8, ItemType) {
    ITEM_TYPE_NONE,
    ITEM_TYPE_MISSILE,
    ITEM_TYPE_ENERGY,
    ITEM_TYPE_SUPER_MISSILE,
    ITEM_TYPE_POWER_BOMB,

    ITEM_TYPE_ABILITY = 1 << 7
};

MAKE_ENUM(u16, CaaDamageType) ENUM_FLAG {
    CAA_DAMAGE_TYPE_NONE                 = 0,
    CAA_DAMAGE_TYPE_BEAM                 = 1 << 0,
    CAA_DAMAGE_TYPE_BOMB_PISTOL          = 1 << 1,
    CAA_DAMAGE_TYPE_MISSILE              = 1 << 2,
    CAA_DAMAGE_TYPE_SUPER_MISSILE        = 1 << 3,
    CAA_DAMAGE_TYPE_POWER_BOMB           = 1 << 4,
    CAA_DAMAGE_TYPE_SPEEDBOOST           = 1 << 5,
    CAA_DAMAGE_TYPE_SPEEDBOOST_ON_GROUND = 1 << 6,
    CAA_DAMAGE_TYPE_SCREW_ATTACK         = 1 << 7,
    CAA_DAMAGE_TYPE_BOMB_CHAIN           = 1 << 12,
    
    CAA_REVEAL_BOMB_BLOCKS = CAA_DAMAGE_TYPE_BEAM | CAA_DAMAGE_TYPE_MISSILE | CAA_DAMAGE_TYPE_SUPER_MISSILE,
    
    TANK_WEAKNESS = CAA_DAMAGE_TYPE_BEAM | CAA_DAMAGE_TYPE_BOMB_PISTOL | CAA_DAMAGE_TYPE_MISSILE | CAA_DAMAGE_TYPE_SUPER_MISSILE | CAA_DAMAGE_TYPE_POWER_BOMB
};


MAKE_ENUM(u8, BlockLifeType) {
    BLOCK_LIFE_TYPE_NONE,
    BLOCK_LIFE_TYPE_NO_NEVER_REFORM,
    BLOCK_LIFE_TYPE_REFORM,
    BLOCK_LIFE_TYPE_BOMB_CHAIN,
    BLOCK_LIFE_TYPE_TANK
};

MAKE_ENUM(u8, BlockSubType) {
    BLOCK_SUB_TYPE_REFORM,
    BLOCK_SUB_TYPE_SQUARE_NO_REFORM,
    BLOCK_SUB_TYPE_NO_REFORM,
    BLOCK_SUB_TYPE_SQUARE_NEVER_REFORM,
    BLOCK_SUB_TYPE_BOMB_CHAIN,

    BLOCK_SUB_TYPE_COUNT
};

MAKE_ENUM(u8, BombChainType) {
    BOMB_CHAIN_TYPE_VERTICAL1,
    BOMB_CHAIN_TYPE_VERTICAL2,
    BOMB_CHAIN_TYPE_VERTICAL3,
    BOMB_CHAIN_TYPE_VERTICAL4,
    BOMB_CHAIN_TYPE_HORIZONTAL1,
    BOMB_CHAIN_TYPE_HORIZONTAL2,
    BOMB_CHAIN_TYPE_HORIZONTAL3,
    BOMB_CHAIN_TYPE_HORIZONTAL4,

    BOMB_CHAIN_TYPE_COUNT
};

MAKE_ENUM(u8, SubBombChainRequest) {
    SUB_BOMB_CHAIN_REQUEST_HORIZONTAL_WHEN_GOING_UP,
    SUB_BOMB_CHAIN_REQUEST_HORIZONTAL_WHEN_GOING_DOWN,
    SUB_BOMB_CHAIN_REQUEST_VERTICAL_WHEN_GOING_LEFT,
    SUB_BOMB_CHAIN_REQUEST_VERTICAL_WHEN_GOING_RIGHT,

    SUB_BOMB_CHAIN_REQUEST_COUNT
};

#endif /* BLOCK_CONSTANTS_H */
