#ifndef CABLE_LINK_CONSTANTS_H
#define CABLE_LINK_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, ActiveTransfer) {
    ACTIVE_TRANSFER_NONE,
    ACTIVE_TRANSFER_CONNECT,
    ACTIVE_TRANSFER_LINK
};

MAKE_ENUM(u8, ConnectStage) {
    CONNECT_STAGE_FADE_MUSIC,
    CONNECT_STAGE_WAIT_CLEAR_SOUND,
    CONNECT_STAGE_MULTIBOOT_INIT,
    CONNECT_STAGE_MULTIBOOT_PROCESS,
    CONNECT_STAGE_TRANSFER_SEND_TRANSFER_ROM,
    CONNECT_STAGE_TRANSFER_COMPLETE,
    CONNECT_STAGE_TRANSFER_SUCCESS,
    CONNECT_STAGE_MULTIBOOT_TIMED_OUT,
    CONNECT_STAGE_BACKED_OUT,
    CONNECT_STAGE_TRANSFER_FAILURE,
    CONNECT_STAGE_SET_ACTIVE_LINK,
    CONNECT_STAGE_RESTORE_AUDIO,
    CONNECT_STAGE_FINISH
};

MAKE_ENUM(u8, TransferResult) {
    TRANSFER_RESULT_NONE,
    TRANSFER_RESULT_SUCCESS,
    TRANSFER_RESULT_BACKED_OUT,
    TRANSFER_RESULT_TIMED_OUT,
    TRANSFER_RESULT_FAILURE,
    TRANSFER_RESULT_SUCCESS2 // Related to number of received images
};

MAKE_ENUM(u8, LinkStage) {
    LINK_STAGE_INIT,
    LINK_STAGE_PROCESS_CONNECTION,
    LINK_STAGE_RECEIVED_GALLERY,
    LINK_STAGE_ERROR0,
    LINK_STAGE_ERROR1,
    LINK_STAGE_UNK5
};

MAKE_ENUM(u8, LinkState) {
    LINK_STATE_START0,
    LINK_STATE_START1,
    LINK_STATE_HANDSHAKE,
    LINK_STATE_INIT_TIMER,
    LINK_STATE_CONN_ESTABLISHED
};

MAKE_ENUM(u8, QueueFull) {
    QUEUE_FULL_NONE,
    QUEUE_FULL_SEND,
    QUEUE_FULL_RECV
};

MAKE_ENUM(u8, LagStatus) {
    LAG_NONE,
    LAG_PARENT,
    LAG_CHILD
};

#endif /* CABLE_LINK_CONSTANTS_H */
