#ifndef GAME_OVER_CONSTANTS_H
#define GAME_OVER_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, GameOverCursorAction) {
    SAMUS_CURSOR_ACTION_LOADING,
    SAMUS_CURSOR_ACTION_MOVING,
    SAMUS_CURSOR_ACTION_SELECTING,

    SAMUS_CURSOR_ACTION_COUNT
};

MAKE_ENUM(u8, GameOverOamId) {
    GAME_OVER_OAM_ID_SUIT_MOVING = 1,
    GAME_OVER_OAM_ID_SUIT_LOADING,

    GAME_OVER_OAM_ID_SUIT_SELECTING = 4,
    GAME_OVER_OAM_ID_SUITLESS_MOVING,
    GAME_OVER_OAM_ID_SUITLESS_LOADING,

    GAME_OVER_OAM_ID_SUITLESS_SELECTING = 8,

    GAME_OVER_OAM_ID_COUNT
};

#endif /* GAME_OVER_CONSTANTS_H */
