#ifndef INTRO_CONSTANTS_H
#define INTRO_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, IntroTextAction) {
    INTRO_TEXT_ACTION_NONE,
    INTRO_TEXT_ACTION_START,
    INTRO_TEXT_ACTION_SPACE,
    INTRO_TEXT_ACTION_SKIP_CHARACTER,
    INTRO_TEXT_ACTION_NEW_LINE,

    INTRO_TEXT_ACTION_COUNT
};

#endif /* INTRO_CONSTANTS_H */
