#ifndef MINIMAP_CONSTANTS_H
#define MINIMAP_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, MinimapUpdateFlag) {
    MINIMAP_UPDATE_FLAG_NONE,
    MINIMAP_UPDATE_FLAG_UPPER_LINE,
    MINIMAP_UPDATE_FLAG_MIDDLE_LINE,
    MINIMAP_UPDATE_FLAG_LOWER_LINE,

    MINIMAP_UPDATE_FLAG_COUNT
};

#define MINIMAP_TILE_BACKGROUND 0x140

#endif /* MINIMAP_CONSTANTS_H */
