#ifndef ACID_WORM_AI_H
#define ACID_WORM_AI_H

#include "types.h"

#define ACID_WORM_POSE_CHECK_SAMUS_ON_ZIPLINE 0x1
#define ACID_WORM_POSE_IDLE_INIT 0x8
#define ACID_WORM_POSE_IDLE 0x9
#define ACID_WORM_POSE_EXTENDED 0xF
#define ACID_WORM_POSE_CHECK_WARNING_ENDED 0x23
#define ACID_WORM_POSE_EXTENDING 0x25
#define ACID_WORM_POSE_RETRACTING 0x27
#define ACID_WORM_POSE_RAISING_ACID 0x29
#define ACID_WORM_POSE_BRINGING_DOWN_ACID 0x2B
#define ACID_WORM_POSE_CHECK_SPAWN 0x42
#define ACID_WORM_POSE_SPAWN_EXTEND 0x43
#define ACID_WORM_POSE_SPAWN_ON_TOP 0x45
#define ACID_WORM_POSE_SPAWN_RETRACT 0x47
#define ACID_WORM_POSE_DYING_INIT 0x62
#define ACID_WORM_POSE_DYING_ANIM 0x67
#define ACID_WORM_POSE_DYING 0x68

void AcidWorm(void);
void AcidWormPart(void);
void AcidWormSpit(void);

#endif /* ACID_WORM_AI_H */