#ifndef GETTING_FULLY_POWERED_SUIT_CUTSCENE
#define GETTING_FULLY_POWERED_SUIT_CUTSCENE

#include "types.h"
#include "macros.h"
#include "structs/cutscene.h"

MAKE_ENUM(u8, GettingFullyPoweredSuitOamId) {
    GETTING_FULLY_POWERED_SUIT_OAM_ID_NONE,
    GETTING_FULLY_POWERED_SUIT_OAM_ID_SPARKLE_GOING_UP,
    GETTING_FULLY_POWERED_SUIT_OAM_ID_SPARKLE_AROUND_RING1,
    GETTING_FULLY_POWERED_SUIT_OAM_ID_SPARKLE_AROUND_RING2,
    GETTING_FULLY_POWERED_SUIT_OAM_ID_RING_BOTTOM,
    GETTING_FULLY_POWERED_SUIT_OAM_ID_RING_TOP,

    GETTING_FULLY_POWERED_SUIT_OAM_ID_COUNT
};

#define OAM_RING_SPARKLES_AMOUNT 6

u8 GettingFullyPoweredSuitMainLoop(void);

#endif /* GETTING_FULLY_POWERED_SUIT_CUTSCENE */
