#ifndef MOTHER_BRAIN_CLOSE_UP_CUTSCENE
#define MOTHER_BRAIN_CLOSE_UP_CUTSCENE

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, MotherBrainCloseUpOamId) {
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_NONE,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_BUBBLE,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_UNUSED_EYE,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_EYE_OPENING,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_ELEVATOR_ANIMATION,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_EYE_OPENED,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_EYE_FOCUSING,

    MOTHER_BRAIN_CLOSE_UP_OAM_ID_COUNT
};

u8 MotherBrainCloseUpMainLoop(void);

#endif /* MOTHER_BRAIN_CLOSE_UP_CUTSCENE */
