#ifndef MOTHER_BRAIN_CLOSE_UP_CUTSCENE
#define MOTHER_BRAIN_CLOSE_UP_CUTSCENE

#include "types.h"

enum MotherBrainCloseUpOamId {
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_BUBBLE = 1,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_UNUSED_EYE,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_EYE_OPENING,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_ELEVATOR_ANIMATION,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_EYE_OPENED,
    MOTHER_BRAIN_CLOSE_UP_OAM_ID_EYE_FOCUSING,

    MOTHER_BRAIN_CLOSE_UP_OAM_ID_END
};

u8 MotherBrainCloseUpMainLoop(void);

#endif /* MOTHER_BRAIN_CLOSE_UP_CUTSCENE */
