#ifndef RIDLEY_LANDING_CUTSCENE
#define RIDLEY_LANDING_CUTSCENE

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, RidleyLandingOamId) {
    RIDLEY_LANDING_OAM_ID_NONE, 
    RIDLEY_LANDING_OAM_ID_MOTHER_SHIP_IN_SPACE, 
    RIDLEY_LANDING_OAM_ID_MOTHER_SHIP_BOTTOM_PART,
    RIDLEY_LANDING_OAM_ID_MOTHER_SHIP_MIDDLE_PART,
    RIDLEY_LANDING_OAM_ID_MOTHER_SHIP_TOP_PART,
    RIDLEY_LANDING_OAM_ID_SMOKE_PARTICLES,
    RIDLEY_LANDING_OAM_ID_SMOKE_PARTICLES_DISAPPEARING,

    RIDLEY_LANDING_OAM_ID_7,
    RIDLEY_LANDING_OAM_ID_RIDLEY,
    RIDLEY_LANDING_OAM_ID_ROCKS,
    RIDLEY_LANDING_OAM_ID_ROCKS_AND_RIDLEY_SHADOW,

    RIDLEY_LANDING_OAM_ID_COUNT
};

u8 RidleyLandingMainLoop(void);

#endif /* RIDLEY_LANDING_CUTSCENE */
