#ifndef RIDLEY_SPAWN_CUTSCENE
#define RIDLEY_SPAWN_CUTSCENE

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, RidleySpawnOamId) {
    RIDLEY_SPAWN_OAM_ID_NONE,
    RIDLEY_SPAWN_OAM_ID_RIDLEY_FLYING_REFLECTION,
    RIDLEY_SPAWN_OAM_ID_RIDLEY_FLYING,
    RIDLEY_SPAWN_OAM_ID_RIDLEY_SCREAMING,
    RIDLEY_SPAWN_OAM_ID_SAMUS,

    RIDLEY_SPAWN_OAM_ID_COUNT
};

u8 RidleySpawnMainLoop(void);

#endif /* RIDLEY_SPAWN_CUTSCENE */
