#ifndef RIDLEY_SPAWN_CUTSCENE
#define RIDLEY_SPAWN_CUTSCENE

#include "types.h"

enum RidleySpawnOamId {
    RIDLEY_SPAWN_OAM_ID_RIDLEY_FLYING_REFLECTION = 1,
    RIDLEY_SPAWN_OAM_ID_RIDLEY_FLYING,
    RIDLEY_SPAWN_OAM_ID_RIDLEY_SCREAMING,
    RIDLEY_SPAWN_OAM_ID_SAMUS,

    RIDLEY_SPAWN_OAM_ID_END
};

u8 RidleySpawnMainLoop(void);

#endif /* RIDLEY_SPAWN_CUTSCENE */
