#ifndef RIDLEY_IN_SPACE_CUTSCENE
#define RIDLEY_IN_SPACE_CUTSCENE

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, RidleyInSpaceOamId) {
    RIDLEY_IN_SPACE_OAM_ID_NONE,
    RIDLEY_IN_SPACE_OAM_ID_LEFT_BLUE_SHIP,
    RIDLEY_IN_SPACE_OAM_ID_RIGHT_BLUE_SHIP,
    RIDLEY_IN_SPACE_OAM_ID_MOTHER_SHIP,
    RIDLEY_IN_SPACE_OAM_ID_MOTHER_SHIP_LEAVING_BACK,
    RIDLEY_IN_SPACE_OAM_ID_MOTHER_SHIP_LEAVING_FRONT,
    RIDLEY_IN_SPACE_OAM_ID_VIEW_OF_SHIP_PARTICLE,

    RIDLEY_IN_SPACE_OAM_ID_7,
    RIDLEY_IN_SPACE_OAM_ID_VIEW_OF_SHIP_PARTICLE2,
    RIDLEY_IN_SPACE_OAM_ID_SHIP_LEAVING_PARTICLE,
    RIDLEY_IN_SPACE_OAM_ID_SHIP_LEAVING_PARTICLE2,

    RIDLEY_IN_SPACE_OAM_ID_COUNT
};

MAKE_ENUM(u8, RidleyInSpaceShipSlot) {
    RIDLEY_IN_SPACE_LEFT_SHIP_SLOT,
    RIDLEY_IN_SPACE_RIGHT_SHIP_SLOT,
    RIDLEY_IN_SPACE_MOTHER_SHIP_SLOT,

    RIDLEY_INSPACE_SHIP_SLOT_COUNT
};

u8 RidleyInSpaceMainLoop(void);

#endif /* RIDLEY_IN_SPACE_CUTSCENE */
