#ifndef STATUE_OPENING_CUTSCENE
#define STATUE_OPENING_CUTSCENE

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, StatueOpeningOamId) {
    STATUE_OPENING_OAM_ID_NONE,
    STATUE_OPENING_OAM_ID_KRAID_IDLE,
    STATUE_OPENING_OAM_ID_KRAID_ACTIVATING,
    STATUE_OPENING_OAM_ID_KRAID_ACTIVATED,
    STATUE_OPENING_OAM_ID_KRAID_OPENED,
    STATUE_OPENING_OAM_ID_RIDLEY_IDLE,
    STATUE_OPENING_OAM_ID_RIDLEY_ACTIVATING,
    STATUE_OPENING_OAM_ID_RIDLEY_ACTIVATED,
    STATUE_OPENING_OAM_ID_RIDLEY_OPENED,

    STATUE_OPENING_OAM_ID_COUNT
};

u8 StatueOpeningMainLoop(void);

#endif /* STATUE_OPENING_CUTSCENE */
