#ifndef ERASE_SRAM_CONSTANTS_H
#define ERASE_SRAM_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, EraseSramOption) {
    ERASE_SRAM_OPTION_QUESTION_NO,
    ERASE_SRAM_OPTION_QUESTION_YES,
    ERASE_SRAM_OPTION_CONFIRM_NO,
    ERASE_SRAM_OPTION_CONFIRM_YES,

    ERASE_SRAM_OPTION_COUNT,

    ERASE_SRAM_OPTION_CHANGED_FLAG = 1 << 7
};

MAKE_ENUM(u32, EraseSramInputAction) {
    ERASE_SRAM_INPUT_ACTION_NONE,
    ERASE_SRAM_INPUT_ACTION_ERASING,
    ERASE_SRAM_INPUT_ACTION_OPENING_SUB_WINDOW
};

MAKE_ENUM(u8, EraseSramOamId) {
    ERASE_SRAM_OAM_ID_CURSOR_NONE,
    ERASE_SRAM_OAM_ID_CURSOR_IDLE,
    ERASE_SRAM_OAM_ID_CURSOR_SELECTING,
    ERASE_SRAM_OAM_ID_QUESTION_WINDOW_NO_SELECTED,
    ERASE_SRAM_OAM_ID_QUESTION_WINDOW_YES_SELECTED,
    ERASE_SRAM_OAM_ID_CONFIRM_WINDOW_NO_SELECTED,
    ERASE_SRAM_OAM_ID_CONFIRM_WINDOW_YES_SELECTED,

    ERASE_SRAM_OAM_ID_COUNT
};

MAKE_ENUM(u32, EraseSramSound) {
    ERASE_SRAM_SOUND_NONE,
    ERASE_SRAM_SOUND_CONFIRM,
    ERASE_SRAM_SOUND_SELECT_YES,
    ERASE_SRAM_SOUND_REFUSE,
    ERASE_SRAM_SOUND_CURSOR,

    ERASE_SRAM_SOUND_COUNT
};

#endif /* ERASE_SRAM_CONSTANTS_H */
