#ifndef TITLE_SCREEN_CONSTANTS_H
#define TITLE_SCREEN_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, TitleScreenType) ENUM_FLAG {
    TITLE_SCREEN_TYPE_FIRST_COMET_ACTIVE    = 1 << 0,
    TITLE_SCREEN_TYPE_FIRST_COMET_ENDED     = 1 << 1,
    TITLE_SCREEN_TYPE_SECOND_COMET_ACTIVE   = 1 << 2,
    TITLE_SCREEN_TYPE_SECOND_COMET_ENDED    = 1 << 3,
    TITLE_SCREEN_TYPE_TOP_SPARKLE_ACTIVE    = 1 << 4,
    TITLE_SCREEN_TYPE_TOP_SPARKLE_ENDED     = 1 << 5,
    TITLE_SCREEN_TYPE_BOTTOM_SPARKLE_ACTIVE = 1 << 6,
    TITLE_SCREEN_TYPE_BOTTOM_SPARKLE_ENDED  = 1 << 7,

    TITLE_SCREEN_TYPE_ALL_SPARKLES_ENDED    = TITLE_SCREEN_TYPE_TOP_SPARKLE_ENDED | TITLE_SCREEN_TYPE_BOTTOM_SPARKLE_ENDED
};

MAKE_ENUM(u8, TitleScreenIdleStage) {
    TITLE_SCREEN_IDLE_STAGE_COMETS,
    TITLE_SCREEN_IDLE_STAGE_TITLE_FADING,
    TITLE_SCREEN_IDLE_STAGE_IDLE
};

MAKE_ENUM(u8, TitleScreenAnimatedPalette) ENUM_FLAG {
    TITLE_SCREEN_ANIMATED_PALETTE_SKY_DECORATIONS = 1 << 0,
    TITLE_SCREEN_ANIMATED_PALETTE_TITLE           = 1 << 1,
    TITLE_SCREEN_ANIMATED_PALETTE_PROMPT          = 1 << 2
};

MAKE_ENUM(u8, TitleScreenOamId) {
    TITLE_SCREEN_OAM_ID_NONE,
    TITLE_SCREEN_OAM_ID_COMET_SPAWNING,
    TITLE_SCREEN_OAM_ID_COMET_APPEARING,
    TITLE_SCREEN_OAM_ID_COMET_FLYING,
    TITLE_SCREEN_OAM_ID_SPARKLE_IDLE,
    TITLE_SCREEN_OAM_ID_SPARKLE_GROWING,
    TITLE_SCREEN_OAM_ID_SPARKLE_DISAPPEARING,

    TITLE_SCREEN_OAM_ID_COUNT
};

MAKE_ENUM(u8, TitleScreenCopyrightSymbol) {
    TITLE_SCREEN_COPYRIGHT_SYMBOL_NONE,
    TITLE_SCREEN_COPYRIGHT_SYMBOL_REGISTERED_TRADEMARK, // ®️
    TITLE_SCREEN_COPYRIGHT_SYMBOL_TRADEMARK // ™️
};

MAKE_ENUM(u8, TitleScreenMenuOption) {
    TITLE_SCREEN_MENU_OPTION_START_GAME,
    TITLE_SCREEN_MENU_OPTION_LANGUAGE
};

#endif /* TITLE_SCREEN_CONSTANTS_H */
